Import('env')

sources = [
	'bytestr.cc',
	'dictionary.cc',
	'integer.cc',
	'list.cc',

	'parser.cc',
	'tokenizer.cc',
]

objs = []
for source in sources:
	objs.append(env.Object(source))

Return('objs')
